config/routes.rb
Rails.application.routes.draw do
  resources :detected_obstacles
  root 'detected_obstacles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detected_obstacle.rb
class DetectedObstacle < ApplicationRecord
    self.per_page = 15
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/detected_obstacles_controller.rb
class DetectedObstaclesController < ApplicationController
  before_action :set_detected_obstacle, only: [:show, :edit, :update, :destroy]

  # GET /detected_obstacles
  # GET /detected_obstacles.json
  def index
    @detected_obstacles = DetectedObstacle.all
                                          .paginate(page: params[:page])
                                          .order('timestamps DESC')
  end

  # GET /detected_obstacles/1
  # GET /detected_obstacles/1.json
  # def show
  # end
  #
  # # GET /detected_obstacles/new
  # def new
  #   @detected_obstacle = DetectedObstacle.new
  # end
  #
  # # GET /detected_obstacles/1/edit
  # def edit
  # end
  #
  # # POST /detected_obstacles
  # # POST /detected_obstacles.json
  # def create
  #   @detected_obstacle = DetectedObstacle.new(detected_obstacle_params)
  #
  #   respond_to do |format|
  #     if @detected_obstacle.save
  #       format.html { redirect_to @detected_obstacle, notice: 'Detected obstacle was successfully created.' }
  #       format.json { render :show, status: :created, location: @detected_obstacle }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @detected_obstacle.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /detected_obstacles/1
  # # PATCH/PUT /detected_obstacles/1.json
  # def update
  #   respond_to do |format|
  #     if @detected_obstacle.update(detected_obstacle_params)
  #       format.html { redirect_to @detected_obstacle, notice: 'Detected obstacle was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @detected_obstacle }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @detected_obstacle.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /detected_obstacles/1
  # # DELETE /detected_obstacles/1.json
  # def destroy
  #   @detected_obstacle.destroy
  #   respond_to do |format|
  #     format.html { redirect_to detected_obstacles_url, notice: 'Detected obstacle was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detected_obstacle
      @detected_obstacle = DetectedObstacle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detected_obstacle_params
      params.require(:detected_obstacle).permit(:time, :distance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detected_obstacles_helper.rb
module DetectedObstaclesHelper
end

app/views/detected_obstacles/_form.html.erb
<%= form_with(model: detected_obstacle, local: true) do |form| %>
  <% if detected_obstacle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detected_obstacle.errors.count, "error") %> prohibited this detected_obstacle from being saved:</h2>

      <ul>
      <% detected_obstacle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time, id: :detected_obstacle_time %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance, id: :detected_obstacle_distance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/detected_obstacles/edit.html.erb
<h1>Editing Detected Obstacle</h1>

<%= render 'form', detected_obstacle: @detected_obstacle %>

<%= link_to 'Show', @detected_obstacle %> |
<%= link_to 'Back', detected_obstacles_path %>

app/views/detected_obstacles/index.html.erb
<div class="row content-header">
  <h3 class="col-xs-9">
    Detected Obstacles
  </h3>
  <div class="col-xs-3 action-buttons text-right">
      <small><i class="fa fa-plus"></i> Detected objects appear here automaticallly </small>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
    <% if @detected_obstacles.present? %>
    <div class="panel panel-default">
      <div class="panel-heading">
        All Detected Obstacle
      </div>
      <div class="panel-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th align="center">Time</th>
              <th align="center">Distance in Centimeters</th>
              <th align="center">Image</th>
            </tr>
          </thead>

          <tbody>
            <% @detected_obstacles.each do |detected_obstacle| %>
              <tr>
                <td><%= detected_obstacle.timestamps.strftime('%B %d, %Y: %H:%M %Z') || 'Time not Recorded' %></td>
                <td align="center"><%= detected_obstacle.distance || 'Distance not Recorded' %></td>
                <td align="center"><%= 'No Image yet' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="text-center">
          <%= will_paginate @detected_obstacles, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
    </div>

    <% else %>
      <h3>No Objects detected yet</h3>
    <% end %>
  </div>
  <!-- count -->

  <div class="col-lg-3">
   <div class="panel panel-default">
     <div class="panel-heading">
       <h4 align="center">Detected Obstacles Count</h4>
     </div>
       <div class="panel-body">
         <h1 align="center"><%= @detected_obstacles.count %></h1>
       </div>
      <div class="divider"></div>
       <div class="panel-footer action">
         <h5 align="center">Tracking Ninja Count</h5>
       </div>
   </div>
 </div>
  <!-- count end -->

app/views/detected_obstacles/new.html.erb
<h1>New Detected Obstacle</h1>

<%= render 'form', detected_obstacle: @detected_obstacle %>

<%= link_to 'Back', detected_obstacles_path %>

app/views/detected_obstacles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @detected_obstacle.time %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @detected_obstacle.distance %>
</p>

<%= link_to 'Edit', edit_detected_obstacle_path(@detected_obstacle) %> |
<%= link_to 'Back', detected_obstacles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ObstacleDetection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default navbar-top">
    <div class="container">
        <nav class="navbar-brand"><%= link_to image_tag('ninja2.png') %></nav>
        <ul id="user_links" class="nav navbar-nav navbar-right">
          <li><h3>Navigation made easier</h3></li>
        </ul>
        <ul id="login_links" class="nav navbar-nav navbar-left">
          <li><h3>Park Easy</h3></li>
        </ul>
    </div>
  </nav>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>